import os

STEAM_CONNECTOR_HOST = os.getenv("STEAM_CONNECTOR_HOST", "localhost")
STEAM_CONNECTOR_PORT = os.getenv("STEAM_CONNECTOR_PORT", "8001")
STEAM_CONNECTOR_TIMEOUT = int(os.getenv("STEAM_CONNECTOR_TIMEOUT", "360"))
STEAM_API_KEY = os.getenv("STEAM_API_KEY", None)
STEAM_API_TIMEOUT = int(os.getenv("STEAM_API_TIMEOUT", "120"))
STEAM_API_MAX_PARALLEL_CONNECTIONS = int(os.getenv("STEAM_API_MAX_PARALLEL_CONNECTIONS", "5"))